version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pgvector_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-pgvector.sh:/docker-entrypoint-initdb.d/init-pgvector.sh

volumes:
  pg_data:
